# @package _group_

checkpoint_file: null
hparams_file: null
labels_file: ${data.build_dir}/tags.txt

seed: 42

trainer:
  gpus: [0]
  num_nodes: 1
  min_epochs: 10
  precision: 32

model:
  warmup_steps: 100
  lr: 1e-3

data:
  # `name` is the predefined dataset which has to be set to empty if using custom dataset
  name: szegedner
  # `field` is the key in the JSON object for the dialogue in raw data files
  text_field: tokens
  label_field: labels
  root: ${hydra:runtime.cwd}/../../data
  # rebuilds the predefined dataset from scratch
  rebuild: false
  batch_size: 64
  num_workers: 8
  # `build_dir` is only used for pre-defined datasets where the download scripts 
  # prepare the datasets given by `name`
  build_dir: ${data.root}/${data.name}
  cache_dir: ${data.build_dir}

  data_pattern: ${data.build_dir}/*.jsonl

