# Config file for train, eval and export params

# training related parameters

# path of the pretrained checkpoint
# used if resuming training or loading
# checkpoint for export or evaluation
ckpt_path: null

no_cuda: false
fp16: false

max_epochs: 3
warmup_prop: 0.0
batch_size: 8
grad_accum_steps: 1

lr: 5e-05
weight_decay: 0.01
adam_epsilon: 1e-08
clip_grad_norm: 1.0

seed: 42

layer_drop_p: 0.1

# choices are xlmr.base (250) and xlmr.large (500)
model_type: "xlmr.base"
force_download: false

data_dir: ???
tfrecord_size: 10000
max_size: 128

# evaluation related parameters

# path of the .jsonl file which will
# be used for evaluation
eval_data_path: ???

# the path of the labels file which was
# used for model finetuning
labels_path: null

# the location of onnx export
onnx_output_dir: ???

